name: flutter_processing2
description: A Flutter version of Processing.
version: 2.0.0-dev.1
homepage: https://github.com/sylvix/flutter_processing2

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  fast_noise: ^2.0.0
  image: ^4.1.7
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  golden_toolkit: ^0.15.0

flutter:
